default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: tasklist_development

production:
  <<: *default
  database: tasklist_production
  username: tasklist
  password: <%= ENV['TASKLIST_DATABASE_PASSWORD'] %>